import { AiWorkflow } from '../../types/content';

/** English mirror of ko/aiWorkflow.ts. At least one honest limitation is required. */
export const aiWorkflow: AiWorkflow = {
  headline: 'Design with AI. Decide what to protect myself.',
  summary:
    'The data map was designed in conversation with AI. But the guardrails were my call: inferences are labeled as estimates, example values are synthetic rather than real, and people appear only at department level. AI raised the speed of design; what to protect was decided by me.',
  guardrails: [
    {
      title: 'Inferences are labeled as estimates',
      description: 'Table descriptions and relations generated by the LLM are visually separated from vetted ones, so the catalog does not become a new source of misunderstanding.'
    },
    {
      title: 'Example values are synthetic only',
      description: 'Serialization structure is reproduced from real code, but every value and ID is fake. Documentation must not become a leak path.'
    },
    {
      title: 'People only at department level',
      description: 'Who looks at which data is aggregated by organization. Personal identifiers never enter the pipeline.'
    },
    {
      title: 'Agents never touch the warehouse directly',
      description: 'Read-only, partition filters required, results aggregated locally. Cost and exposure limits are held by a wrapper, not by human attention.'
    },
    {
      title: 'Anything needing approval stops and asks',
      description: 'Production access, destructive commands, and outbound transfers require a human confirmation even in auto-approve mode.'
    }
  ],
  limitations: [
    'AI analysis reports held up as far as "serve the metric → assist the interpretation", but they are not at the stage of replacing judgment. Whether to adopt them was left as a decision on the PoC results.',
    'Without separating inference from vetting, the catalog itself becomes a new source of misunderstanding. That is why the "estimate" label is enforced.'
    // TODO(kyo): one concrete wrong answer or failure produced by AI (this will be the most trusted line in the section)
  ],
  diagram: `flowchart LR
  H[Human · question and judgment] --> AG[Coding agent]
  AG --> W[Query · schema wrapper<br/>read-only · partition guard]
  W --> DW[(Warehouse)]
  DW --> L[Local aggregation · only summaries enter context]
  L --> H
  SRC[Code · DDL · usage logs] --> X[LLM extraction]
  X --> T{Vetted?}
  T -->|yes| KG[Knowledge graph · confirmed]
  T -->|no| KG2[Knowledge graph · labeled estimate]
  KG & KG2 --> MAP[Static data map]`
};
